### PR TITLE
Add a doc with CentOS CI testing commands

### LINKED ISSUE #292: document centos ci "commands"
The centos ci integration we use has a number of commands that can be issued to it as a comment on github. I have difficulty remembering these commands. I would like to document these commands somewhere and/or have the most common ones in a pull request template  (rerun a test).

### PR DESCRIPTION
**Pull request by anoopcs9**
Fixes #292 

Depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/13

### CODE REVIEW

**Review by phlogistonjohn — DISMISSED** [review]
LGTM.

I do wonder still if we should have a pull request template that links here ;-)

**Comment by anoopcs9** [comment]
> I do wonder still if we should have a pull request template that links here ;-)

Sure. I was reluctant to add a PR template with only reference to the proposed doc.

Feel free to raise a PR which introduces a PR template with necessary link to the proposed doc.

**Review by spuiuk — APPROVED** [review]
Ack

**Comment by anoopcs9** [comment]
@Mergifyio rebase

**Pull request merged**
