### PR TITLE
workflows: add configuration to do a CI run on a release branch

### PR DESCRIPTION
**Pull request by phlogistonjohn**
This branch does not exist yet.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Re running centos, but note that centos failures are just unrelated to the github ci only changes in this PR.

**Review by synarete — APPROVED** [review]
LGTM

**Review by spuiuk — APPROVED** [review]
ACKed by: Sachin Prabhu <sprabhu@redhat.com>

**Comment by anoopcs9** [comment]
> Re running centos, but note that centos failures are just unrelated to the github ci only changes in this PR.

There was a logical error in how these doc only changes were detected which is now [fixed](https://github.com/anoopcs9/samba-centosci/commit/9f1119327bd4c20b493aec517e712400fccb56ad) and should return success asap for following paths:

`docs` `.md` `LICENSE` `.codespellignore` `.codespellrc` `.github` `.gitignore` `.golangci.yaml` `.revive.toml` `.yamllint.yaml`

**Comment by phlogistonjohn** [comment]
Very cool!

**Pull request merged**
