### PR TITLE
Bump minimum Go version to 1.19

### PR DESCRIPTION
**Pull request by anoopcs9**
depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/28

### CODE REVIEW

**Comment by anoopcs9** [comment]
Not urgent, we could wait till Go 1.21 is released(may be in 2-3 weeks time).

**Review by phlogistonjohn — DISMISSED** [review]
I'm perpetually perplexed by the precise meaning of the go version present in the go.mod file. I'm pretty positive that they're even planning to change it. Usually I prefer to see the build versions change but not the mod file. But I am not going to pester you about it.

**Comment by anoopcs9** [comment]
> Not urgent, we could wait till Go 1.21 is released(may be in 2-3 weeks time).

Go [1.21](https://go.dev/doc/go1.21) is out now.

**Review by obnoxxx — CHANGES_REQUESTED** [review]
I think "build:" is not the appropriate componeb for both the commit and the PR since this PR changes both the build itself and the github workflow actions. 

I think these two changes should be separated in two commits and maybe two dependent PRs ...

**Review by phlogistonjohn — DISMISSED** [review]
Approved.

I agree with @obnoxxx that the `build` commit probably should be two commits but it doesn't bother me enough to block the PR.

Unfortunately, we're now going to continue to play catch-up because Go 1.21 has been released, making 1.19 now out of support so we should follow up with updates to 1.20... at least for the CI and containers (hopefully not go.mod again)

**Comment by anoopcs9** [comment]
> Approved.
> 
> I agree with @obnoxxx that the `build` commit probably should be two commits but it doesn't bother me enough to block the PR.

Updated once more.

**Review by phlogistonjohn — COMMENTED** [review]
LGTM, thanks

**Review by phlogistonjohn — APPROVED** [review]
LGTM

**Comment by phlogistonjohn** [comment]
@obnoxxx or @synarete -- a 2nd review please

**Review by obnoxxx — APPROVED** [review]

**Pull request merged**
