### PR TITLE
github actions: test container build on PRs

### PR DESCRIPTION
**Pull request by obnoxxx**
Signed-off-by: Michael Adam <obnox@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
After merging PR #26, I noticed that the push action failed on the container build with `no space left on device`.
Therefore, I am adding the container build to the PR tests as well (not the push though...).

**Comment by obnoxxx** [comment]
OK, this doesn't really pass. I just added an ` || df -h` after the make command.
It fails with no space left, but the df does not seem to confirm that... 🤷

**Comment by obnoxxx** [comment]
OK... Added a docker build flavour, and that passes...
Not sure what's up with podman and space consumption.

**Comment by obnoxxx** [comment]
OK, so ...
* container build using docker works
* container build using podman fails due to no space left on device

@phlogistonjohn , should we just use docker for now, and have a PR check job for both podman and docker?

**Comment by obnoxxx** [comment]
@phlogistonjohn, I changed this to:

1. build with both podman and docker in PR verification (podman currently fails)
2. change the push job to use docker (which should work for now)

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn, I changed this to:
> 
>     1. build with both podman and docker in PR verification (podman currently fails)
> 
>     2. change the push job to use docker (which should work for now)

Sounds good.
As for the podman issue itself we should check what version these builder vms come with. We could also see if we can pull in a newer release if its old, and see if that improves things. If not, perhaps we should report the issue.

**Comment by obnoxxx** [comment]
> > @phlogistonjohn, I changed this to:
> > ```
> > 1. build with both podman and docker in PR verification (podman currently fails)
> > 
> > 2. change the push job to use docker (which should work for now)
> > ```
> 
> Sounds good.

Should we push it as is then and let the podman build fail for now?

> As for the podman issue itself we should check what version these builder vms come with. We could also see if we can pull in a newer release if its old, and see if that improves things. If not, perhaps we should report the issue.

https://github.com/actions/virtual-environments/issues/709
https://github.com/actions/virtual-environments/issues/1860
https://github.com/containers/podman/issues/3846

**Review by phlogistonjohn — APPROVED** [review]

**Pull request merged**
