### PR TITLE
integration tests: test SmbShares enabling grouping and clustering 

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Depends on #240 

This series is really two parts: first it fixes some test flakiness I was seeing on my local system. The CI wasn't being as flaky but I think these changes will make it more reliable too. Second, I add one additional test case to verify that combining the two SmbShare scaling modes, grouping and clustering, can work properly together.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Leaving as a draft until #240 is merged.

**Review by synarete — DISMISSED** [review]
LGTM

**Comment by phlogistonjohn** [comment]
rebased and fixed the title :-)

**Review by obnoxxx — APPROVED** [review]
lgtm, looks like a great improvement to test code and coverage! approving since @synarete already wrote lgtm before ...

**Pull request merged**
