### PR TITLE
More integration test organizational cleanups

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Depends on: #223

There were far too many context.TODO calls in the integration tests and they were reproducing. This also prepares for adding information about the parameters of the test for logging/tracking purposes.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
I'll keep re-running the centos ci job as needed but I'll point out that the PR that depends on this #225 resolves some of the common ci flakes. I'd appreciate it if the team reviewed this without worrying too much about having the CI pass as I may opt to just ignore centosci until #225.

**Comment by phlogistonjohn** [comment]
@synarete @spuiuk @anoopcs9 - please review. Despite our current CI woes I do think this is an improvement. I am willing to merge this even with some CI failures if we agree the failures are not due to the code change in question while we work through the CI issues.  Thanks!

**Review by spuiuk — APPROVED** [review]
Apart from that unused global declared. TestIDKey, eveything thing is fine.

Acked-by: Sachin Prabhu

**Pull request merged**
