### PR TITLE
Improve developer workflow in makefile and docs

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Previously, the docs didn't explain that the example YAML snippets were to be added to a stock kustomization.yaml, nor did it explain that the makefile could help create this kustomization.yaml.
Now we  can easily initialize the developer dir with `make developer-dir DEVELOPER=1` and we improve the docs to match.

Fixes: #136

### CODE REVIEW

**Comment by synarete** [comment]
LGTM. 
While reviewing, I noticed two minor issues, which worth squash into this PR: 
https://github.com/synarete/samba-operator/commit/2fdedbcda3ce2d788333e34d417debb0db622325
https://github.com/synarete/samba-operator/commit/846a99f615f003cec88a0610630c124d907d9937

**Review by spuiuk — DISMISSED** [review]
Looks Good.

**Comment by phlogistonjohn** [comment]
PR updated, PTAL.  @spuiuk @synarete

**Review by spuiuk — DISMISSED** [review]
ACK

**Comment by phlogistonjohn** [comment]
I think the CI is actually failing due to this PR's changes. It is certainly going to be part of the makefile changes, not the doc text but I need to hunt down what it is because the changes should have been minor.

**Comment by phlogistonjohn** [comment]
PR updated. I finally figured out the issue wrt why the makefile changes were breaking the CI. Details are in a comment in the change. When you have a free moment, PTAL @spuiuk @synarete

**Review by spuiuk — APPROVED** [review]
ACK

**Pull request merged**
