### PR TITLE
implement customizing behavior of shares

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Depends on PR #35. Please review that first.

Apologies for the number of patches in this PR. I couldn't see a good point to break this up at. Pretty much all of this is about setting up and maintaining the configmap that configures sambacc (which in turn configures samba and the container env).

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
Ugh. Bad rebase. Will fix.

**Review by obnoxxx — CHANGES_REQUESTED** [review]
For some reason, GitHub can't automatically rebase/update this and speaks of merge conflicts. I can't confirm those in my local checkout. Please update the PR. @phlogistonjohn

**Comment by phlogistonjohn** [comment]
Updated.

**Review by obnoxxx — APPROVED** [review]
lgtm

**Pull request merged**
